name: 🐞 Bug 报告
description: 提交一个 Bug。
title: "[Bug]: "
labels: ["🐛 bug", "pending triage"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您抽出时间报告 Bug。请填写以下详细信息，以帮助我们快速重现和修复问题。

        - 请将您的问题标题格式化为：`[模块/组件名/范围]：xxx 简短描述`
        - 在提交之前，请检查是否已存在类似的问题。
        - 如果可能，请提供相关的日志、API 请求、或最小可重现的代码仓库。

  - type: textarea
    id: description
    attributes:
      label: 问题描述
      description: 发生了什么？您期望的结果是什么？
      placeholder: 请清晰地描述这个 Bug。
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: 重现步骤
      description: "您是如何触发这个 Bug 的？请一步步地告诉我们。"
      placeholder: |
        1. 使用以下参数调用 `/api/xxx` 端点...
        2. 预期返回状态码 200，但实际返回 500
        3. 在应用日志中观察到以下异常及完整的堆栈跟踪...
    validations:
      required: true

  - type: textarea
    id: extra
    attributes:
      label: 补充信息 (可选)
      description: 如果可能，提供额外细节（例如：环境、日志、配置）以帮助我们调查。
      placeholder: |
        - 操作系统 (OS): 
        - Java 版本 (Java Version): 
        - Spring Boot 版本:
        - Maven/Gradle 版本:
        - 数据库 (Database):
        - 任何相关的日志或完整的堆栈跟踪:

  - type: checkboxes
    id: checklist
    attributes:
      label: 核对清单
      description: 在提交问题之前，请确保您已完成以下操作。
      options:
        - label: 我已经检查过，没有重复的 Bug 报告。
          required: true
        - label: 我已经提供了清晰且可重现的步骤。
          required: true
