# 服务基础配置
server:
  port: 8080
  servlet:
    context-path: /api

# 文件服务配置
file:
  upload-dir: /var/uploads
#  upload-dir: E:\file
  max-file-size: 1
  expiration: 10080 # 文件 token 有效期（分钟）默认 7 天

# Spring 数据源配置
spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  application:
    name: admin-x
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/admin_x?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  # JPA/Hibernate 配置
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 5000ms
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: smtp.qq.com # 你的 smtp 服务器
    port: 465 # 端口
    username: xxx # 发送验证码的邮箱
    password: xxx # smtp 授权码
    properties:
      mail.smtp.ssl.enable: true # 是否开启 ssl 加密

# mail 验证开关
email:
  verification-enabled: true # true 开启邮箱验证，false 关闭邮箱验证
  subject: "验证码" # 邮件主题
  content-template: "您的验证码是: %s，请在 5 分钟内使用"
  code-count: 6 # 验证码位数
  expire-seconds: 300 # 过期时间 (秒)
  ignore-case: true # 是否忽略大小写 (默认不忽略)
  key-head: "mail_captcha:" # 验证码 (key) 的头
  team-name: "Admin x <%s>" # 邮件标题

# MyBatisPlus 配置
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# JWT 配置（需与 JwtTokenUtil 中的字段对应）
jwt:
  secret: 256-bit-secret-1234567890abcdefghijklmnopqrstuvwxyz
  expiration: 604800 # 过期时间（秒）
  token-header: Authorization
  token-prefix: "Bearer "

knife4j:
  enable: true  # 是否开启接口文档，默认开启
  production: false # 是否为生产环境，默认否
  setting:
    language: zh-CN
  # 添加上下文路径配置
  documents:
    - group: 默认
      name: 接口文档
      locations: classpath:group.json

# 日志配置
logging:
  level:
    root: info
    com.bytescheduler.adminx: debug  # 项目包日志级别
    org.springframework.security: debug
  file:
    name: logs/app.log

# 验证码配置
captcha:
  width: 160
  height: 60
  code-count: 5 # 验证码位数
  interference-count: 20 # 影响线，越高越复杂
  expire-seconds: 60 # 过期时间 (秒)
  ignore-case: true # 是否忽略大小写 (默认不忽略)
  key-head: "captcha:" # 验证码 (key) 的头

# 服务限流配置
rate:
  limit:
    max-requests: 15 # 单位时间内最多连接次数
    interval-seconds: 20 # 20（秒）为一个单位
    ban-seconds: 1800 # 封禁时间（秒）

# 接口签名配置
signature:
  max-time-diff: 5000 # 签名有效期 5 秒
  secret-key: 8D7F2A9C4E5B1F3A6C9D2E8F7B1A5C3D

# QQ 登录配置
qq:
  app-id: 102805332 # APP ID
  app-key:
  redirect-uri: https://byteout.cn/login
  access-token-url: https://graph.qq.com/oauth2.0/token
  openid-url: https://graph.qq.com/oauth2.0/me
  user-info-url: https://graph.qq.com/user/get_user_info

# github 登录配置
github:
  client-id: Ov23lihR664NL115OifZ
  client-secret:
  redirect-uri: https://byteout.cn/login
  authorization-uri: https://github.com/login/oauth/authorize
  token-uri: https://github.com/login/oauth/access_token
  user-info-uri: https://api.github.com/user